### ISSUE TITLE
Inconsistency in generation of get-operations for boolean attributes

### ISSUE THREAD

**Issue by AlexanderWichmann** [MDE4CPP/MDE4CPP#26]
Following rules for generating boolean get-operations are existing:
- in '*.ecore* models: type.name = 'EBoolean' then getter starts with 'is' (ecore4CPP)
- in '*.uml* models: type.name = 'Boolean' then getter starts with 'is' (UML4CPP)

### Problems:
- In 'uml.ecore' model, there are properties with type 'Boolean'. This lead to getter name starting with 'get' for boolean attributes. ('EBoolean' <> 'Boolean')
- fUML4CPP fails in generation classifier object classes. (e.g. call of LiteralBoolean::isValue()' is generated, but acutally, LiteralBoolean.hpp only includes 'getValue()' operation.

### Solutions:
- Modify ecore4CPP: if type.name = 'Boolean', also generate get-operations starting with 'is'
- Modify uml.ecore: change types of attributes to 'EBoolean'

- in both options: fix code fragments inside fUML.ecore

### Current hotfix:
- fUML4CPP updated: add specialized generation of attribute calling for uml models

**Comment by Maschotta** [comment]
Solved with version 1.3
