### ISSUE TITLE
Support std::map and std::unordered_map for abstract classes

### ISSUE THREAD

**Issue by svdev** [MDE4CPP/MDE4CPP#29]
Let's say I have the following Ecore metamodel:

```
@namespace(uri="http://example.org/people/1.0", prefix="people")
package example;

abstract class Property
{
	attr String name;		
}
class Number extends Property
{
	attr double value;
}
class Address extends Property
{
	attr String street;
	attr String nr;
}
class Person
{	
	!ordered attr ecore.EMap<String, Property> meta;
}
```

Currently the generated 'meta' property getter signature for `Person` class is as follows:

`	virtual std::map<std::string, example::Person> getMeta() const = 0;`
	
This causes errors in compilation because of map initialization.

Because `Property` is an abstract class, I would expect the map values to be `std::unique_ptr<example::Person>` as follows:

`	virtual std::map<std::string, std::unique_ptr<example::Person>> getMeta() const = 0;`
	
At the same time, I would expect if the declaration of `meta` to be `!ordered` instead of `ordered` to use `std::unordered_map` as follows:
 
`	virtual std::unordered_map<std::string, std::unique_ptr<example::Person>> getMeta() const = 0;`

**Comment by Maschotta** [comment]
Add support of unorderedMap and support of additional std::template classes for self defined attribute types for ecore4CPP and UML4CPP (std::vector, std::List, std::map). Add ecore and UML test example:

![unorderedMap class diagram](https://user-images.githubusercontent.com/21172883/109992438-8e460d80-7d0b-11eb-93bd-fca700902541.jpg)
