### ISSUE TITLE
evaluate upper / lower bound

### ISSUE THREAD

**Issue by Maschotta** [MDE4CPP/MDE4CPP#7]

**Comment by Maschotta** [comment]
add .toLowerFirst() for namespace definition. 

Problem: uml-Reflection model(s ecore.uml / uml.uml use) UpperFirst Namespace to differ ecor.ecore/uml.ecore

**Comment by AlexanderWichmann** [comment]
1. What has an lower and upper bound (of Property multiplicites) to do with upper / lower case of namespaces?
2. Why is a new solution necessary? Is the already existing solution not acceptable?

**Comment by Maschotta** [comment]
uodates handling of multiplicity
